modLoader="javafml"
loaderVersion="[29,)"
issueTrackerURL="https://github.com/bageldotjpg/BuzzierBees/issues"

[[mods]]
modId="thwomp"
version="${file.jarVersion}"
displayName="Thwomp"
displayURL="https://discord.gg/zVBFsXp"
logoFile="thwomp"
authors="bageldotjpg & snake block"
credits="gaming"

description='''
poggers
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.thwomp]]
    modId="forge"
    mandatory=true
    versionRange="[29,)"
    ordering="NONE"
    side="BOTH"
